In [33]:
import numpy as np
import pandas as pd
from dateutil import parser

Month3:
Week 4:
Assignment: Cleaning and Analyzing Product Inventory and Supplier Data using Pandas
Scenario
You are working as a junior data analyst at a small retail company.
The company maintains a spreadsheet that tracks product inventory and supplier information, but the data has not been maintained properly. Your task is to create a sample dataset, load it into Pandas, identify issues, clean the data, and perform some basic analysis.

Part 1: Create a Messy Dataset
Create a small dataset that contains at least 15-20 rows and the following 8 columns:
Column Name                        Description
Product_ID             Unique product code (e.g., P001, P002, …)  but include a duplicate or two
Product_Name           Name of the product (some names may be missing or inconsistently capitalized)
Category               Product category (e.g., “Electronics”, “electronics”, “ELECTRONICS”)
Supplier               Supplier name (some duplicates or spelling inconsistencies allowed)
Quantity               Number of units in stock (include a few missing or negative values)
Unit_Price             Price per unit (include some unrealistic or missing values)
Reorder_Level          Minimum quantity before restocking is needed
Last_Update            Date when the record was last updated (some invalid or missing dates)

Example of inconsistencies you should include:
        Missing values (NaN or blank cells)
        Duplicated rows
        Mixed capitalization ("Laptop", "laptop", "LAPTOP")
        Wrong data types (e.g., "twenty" instead of 20)
        Negative or extremely high prices or quantities
        Inconsistent date formats (2025/01/10)
        

Part 2: Load and Inspect the Dataset

Using Pandas, perform the following:
    1. Import the dataset into a DataFrame.
    2. Display the first and last 5 rows.
    3. Show basic information about the dataset using .info() and .describe().
    4. Identify missing values and duplicated rows.



Part 3: Clean the Data

Perform appropriate cleaning steps:
    1. Handle missing values: decide whether to fill or drop them.
    2. Remove duplicate rows.
    3. Standardize text: make all Product_Name, Category, and Supplier lowercase (or title case).
    4. Fix data types: convert columns to proper numeric or datetime types.
    5. Handle incorrect values:
            Replace or drop rows with negative or unrealistic prices/quantities.
            Standardize date formats in Last_Updated.
            

Part 4: Analyze and Sort the Data

Use Pandas to answer the following:
    1. Which products need restocking (where Quantity < Reorder_Level)?
    2. What is the average unit price per category?
    3. Which supplier provides the most products?
    4. List the top 5 most expensive products.
    5. Sort the cleaned dataset by Category and then by Unit_Price in descending order.

Deliverables
Submit the following files:
    1. A Jupyter Notebook (inventory_analysis.ipynb) with:
            Your Pandas code and explanations
            Answers to all analysis questions

In [34]:
#Part 1: Create a Messy Dataset
#Create a small dataset that contains at least 15-20 rows and the following 8 columns:
#Column Name                        Description
#Product_ID             Unique product code (e.g., P001, P002, …)  but include a duplicate or two
#Product_Name           Name of the product (some names may be missing or inconsistently capitalized)
#Category               Product category (e.g., “Electronics”, “electronics”, “ELECTRONICS”)
#Supplier               Supplier name (some duplicates or spelling inconsistencies allowed)
#Quantity               Number of units in stock (include a few missing or negative values)
#Unit_Price             Price per unit (include some unrealistic or missing values)
#Reorder_Level          Minimum quantity before restocking is needed
#Last_Update            Date when the record was last updated (some invalid or missing dates)

#Example of inconsistencies you should include:
        #Missing values (NaN or blank cells)
        #Duplicated rows
        #Mixed capitalization ("Laptop", "laptop", "LAPTOP")
       #Wrong data types (e.g., "twenty" instead of 20)
        #Negative or extremely high prices or quantities
       #Inconsistent date formats (2025/01/10)
        
sample_data = {
    
    "Product_ID": ["P001", "P002", "P003", "P004", "P005", "P006", "P007", "P008", "P009", "P010", "P011", "P012", "P013", "P014", "P015",
                   "P016", "P017", "P018", "P018", "P019"],
    
    "Product_Name": ["Laptop", "laptop", "SMARTPHONE", "Headphones", "Tablet", "TABLET", "Office Chair", "Desk", "Printer", "printer", "Mouse",
                     "Keyboard", "Monitor", "USB Cable", "Webcam", "Router", "router", "Speaker", "Speaker", "External Hard Drive"],
                                                                                     
    "Category": ["Electronics", "electronics", "ELECTRONICS", "Electronics", "electronics", "Furniture", "furniTURE","FURNITURE", "Electronics", 
                 "electronics", "Accessories", "accessories", "Electronics", "ACCESSORIES", "Electronics", "Electronics", "electronics", 
                 "Electronics", "Electronics", "Electronics"],
    
    "Supplier": ["TechSource Ltd", "Tech Source Ltd", "MobileHub", "SoundPro", "Mobile Hub", "HomeStyle", "Home Style", "FurniCo", "PrintWorld",
                 "Print World", "TechSource Ltd", "TechSOURCE Ltd", "VisionTech", "CableKing", "Vision Tech", "NetConnect", "Net Connect", "SoundPro",
                 "SoundPro", "DataStore"], 
    
    "Quantity": [25, 15, 50, 5, "NaN", 18, 17, 100, 12, 12, 200, "NaN", 9, 10, 14, "NaN", 5, 60, 60, 3], 
    
    "Unit_Price": [850, 870, 650, 45, 300, 120,"NaN", 99999, 150, 150, 25, 40, 220, 10555, 75, 130, 130, 85, 85, 5000],
    
    "Reorder_Level": [10, 8, 20, 12, 15, 5, 10, 25, 6, 6, 30, 20, 10, 50, 8, 5, 5, 15, 15, 7], 
    
    "Last_Update": ["2025-01-10", "10/02/2025", "2025/03/15", "15-04-2025", "2025-05-01", "2025/06/12", "2025-13-01", "07/15/2025", "2025-07-20",
                    "2025-07-20", "2025/08/01", "2025-08-05","August 10th, 2025", "2025-09-10", "09-15-2025", "2025/10/05", "2025-10-05", "2025/11/11",
                    "2025/11/11", "2025-12-01"]
 
}

In [35]:
#Part 2: Load and Inspect the Dataset
#Using Pandas, perform the following:
  #  1. Import the dataset into a DataFrame.

data_frame = pd.DataFrame(sample_data)

data_frame

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit_Price,Reorder_Level,Last_Update
0,P001,Laptop,Electronics,TechSource Ltd,25,850,10,2025-01-10
1,P002,laptop,electronics,Tech Source Ltd,15,870,8,10/02/2025
2,P003,SMARTPHONE,ELECTRONICS,MobileHub,50,650,20,2025/03/15
3,P004,Headphones,Electronics,SoundPro,5,45,12,15-04-2025
4,P005,Tablet,electronics,Mobile Hub,NaN,300,15,2025-05-01
5,P006,TABLET,Furniture,HomeStyle,18,120,5,2025/06/12
6,P007,Office Chair,furniTURE,Home Style,17,NaN,10,2025-13-01
7,P008,Desk,FURNITURE,FurniCo,100,99999,25,07/15/2025
8,P009,Printer,Electronics,PrintWorld,12,150,6,2025-07-20
9,P010,printer,electronics,Print World,12,150,6,2025-07-20
10,P011,Mouse,Accessories,TechSource Ltd,200,25,30,2025/08/01
11,P012,Keyboard,accessories,TechSOURCE Ltd,NaN,40,20,2025-08-05
12,P013,Monitor,Electronics,VisionTech,9,220,10,"August 10th, 2025"
13,P014,USB Cable,ACCESSORIES,CableKing,10,10555,50,2025-09-10
14,P015,Webcam,Electronics,Vision Tech,14,75,8,09-15-2025
15,P016,Router,Electronics,NetConnect,NaN,130,5,2025/10/05
16,P017,router,electronics,Net Connect,5,130,5,2025-10-05
17,P018,Speaker,Electronics,SoundPro,60,85,15,2025/11/11
18,P018,Speaker,Electronics,SoundPro,60,85,15,2025/11/11
19,P019,External Hard Drive,Electronics,DataStore,3,5000,7,2025-12-01

In [36]:
# Convert dataframe into csv file  to_csv()
# Create a folder (data) on your vs code to save the employee_dataset in a folder
# You can also save it without creating any folder, just that you won't add data to the instruction given to your code. 
# index=False => not to include the index numbers 

data_frame.to_csv("data/inventory_analysis.csv", index=False)

df = pd.read_csv("data/inventory_analysis.csv")

df

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit_Price,Reorder_Level,Last_Update
0,P001,Laptop,Electronics,TechSource Ltd,25.0,850.0,10,2025-01-10
1,P002,laptop,electronics,Tech Source Ltd,15.0,870.0,8,10/02/2025
2,P003,SMARTPHONE,ELECTRONICS,MobileHub,50.0,650.0,20,2025/03/15
3,P004,Headphones,Electronics,SoundPro,5.0,45.0,12,15-04-2025
4,P005,Tablet,electronics,Mobile Hub,NaN,300.0,15,2025-05-01
5,P006,TABLET,Furniture,HomeStyle,18.0,120.0,5,2025/06/12
6,P007,Office Chair,furniTURE,Home Style,17.0,NaN,10,2025-13-01
7,P008,Desk,FURNITURE,FurniCo,100.0,99999.0,25,07/15/2025
8,P009,Printer,Electronics,PrintWorld,12.0,150.0,6,2025-07-20
9,P010,printer,electronics,Print World,12.0,150.0,6,2025-07-20
10,P011,Mouse,Accessories,TechSource Ltd,200.0,25.0,30,2025/08/01
11,P012,Keyboard,accessories,TechSOURCE Ltd,NaN,40.0,20,2025-08-05
12,P013,Monitor,Electronics,VisionTech,9.0,220.0,10,"August 10th, 2025"
13,P014,USB Cable,ACCESSORIES,CableKing,10.0,10555.0,50,2025-09-10
14,P015,Webcam,Electronics,Vision Tech,14.0,75.0,8,09-15-2025
15,P016,Router,Electronics,NetConnect,NaN,130.0,5,2025/10/05
16,P017,router,electronics,Net Connect,5.0,130.0,5,2025-10-05
17,P018,Speaker,Electronics,SoundPro,60.0,85.0,15,2025/11/11
18,P018,Speaker,Electronics,SoundPro,60.0,85.0,15,2025/11/11
19,P019,External Hard Drive,Electronics,DataStore,3.0,5000.0,7,2025-12-01

In [37]:
#  2. Display the first and last 5 rows.
# first 5 rows 
df.head()

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit_Price,Reorder_Level,Last_Update
0,P001,Laptop,Electronics,TechSource Ltd,25.0,850.0,10,2025-01-10
1,P002,laptop,electronics,Tech Source Ltd,15.0,870.0,8,10/02/2025
2,P003,SMARTPHONE,ELECTRONICS,MobileHub,50.0,650.0,20,2025/03/15
3,P004,Headphones,Electronics,SoundPro,5.0,45.0,12,15-04-2025
4,P005,Tablet,electronics,Mobile Hub,NaN,300.0,15,2025-05-01

In [38]:
#  2. Display the first and last 5 rows.
# last 5 rows

df.tail()

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit_Price,Reorder_Level,Last_Update
15,P016,Router,Electronics,NetConnect,NaN,130.0,5,2025/10/05
16,P017,router,electronics,Net Connect,5.0,130.0,5,2025-10-05
17,P018,Speaker,Electronics,SoundPro,60.0,85.0,15,2025/11/11
18,P018,Speaker,Electronics,SoundPro,60.0,85.0,15,2025/11/11
19,P019,External Hard Drive,Electronics,DataStore,3.0,5000.0,7,2025-12-01

In [39]:
#  3. Show basic information about the dataset using .info() and .describe().
# using .info() 

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Product_ID     20 non-null     str
 1   Product_Name   20 non-null     str
 2   Category       20 non-null     str
 3   Supplier       20 non-null     str
 4   Quantity       17 non-null     float64
 5   Unit_Price     19 non-null     float64
 6   Reorder_Level  20 non-null     int64
 7   Last_Update    20 non-null     str
dtypes: float64(2), int64(1), str(5)
memory usage: 1.4 KB

In [40]:
 # .describe()
# The .describe() method in the pandas library is used to generate a quick, comprehensive statistical summary of a DataFrame or Series.
# It helps you understand the distribution of your data, identify potential outliers, and get an overview of central tendencies
# By default, .describe() excludes missing values (NaN) and adapts its output based on the data type
# 1. count , 2. mean , 3. std , 4. min , 5. 25% , 6. 50% , 7. 75% , 8. max

df.describe()

         Quantity    Unit_Price  Reorder_Level
count   17.000000     19.000000      20.000000
mean    36.176471   6288.368421      14.100000
std     49.773531  22836.420570      10.982762
min      3.000000     25.000000       5.000000
25%     10.000000     85.000000       6.750000
50%     15.000000    150.000000      10.000000
75%     50.000000    750.000000      16.250000
max    200.000000  99999.000000      50.000000

In [41]:
 #  4. Identify missing values and duplicated rows.

df.isnull().sum()

Product_ID       0
Product_Name     0
Category         0
Supplier         0
Quantity         3
Unit_Price       1
Reorder_Level    0
Last_Update      0
dtype: int64

In [42]:
#  4. Identify missing values and duplicated rows.

df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18     True
19    False
dtype: bool

In [43]:
# Part 3: Clean the Data

# Perform appropriate cleaning steps:
    # 1. Handle missing values: decide whether to fill or drop them.
#handling misisng values in Quantity colunm

df["Quantity"] = df["Quantity"].fillna(df["Quantity"].median())

df["Quantity"]

0      25.0
1      15.0
2      50.0
3       5.0
4      15.0
5      18.0
6      17.0
7     100.0
8      12.0
9      12.0
10    200.0
11     15.0
12      9.0
13     10.0
14     14.0
15     15.0
16      5.0
17     60.0
18     60.0
19      3.0
Name: Quantity, dtype: float64

In [44]:
# Perform appropriate cleaning steps:
    # 1. Handle missing values: decide whether to fill or drop them.

#handling misisng values in Unit_Price colunm

df["Unit_Price"] = df["Unit_Price"].fillna(df["Unit_Price"].median())

df["Unit_Price"]

0       850.0
1       870.0
2       650.0
3        45.0
4       300.0
5       120.0
6       150.0
7     99999.0
8       150.0
9       150.0
10       25.0
11       40.0
12      220.0
13    10555.0
14       75.0
15      130.0
16      130.0
17       85.0
18       85.0
19     5000.0
Name: Unit_Price, dtype: float64

In [45]:
# 2. Remove duplicate rows.

df["Product_ID"].to_list()

df["Product_ID"]

0     P001
1     P002
2     P003
3     P004
4     P005
5     P006
6     P007
7     P008
8     P009
9     P010
10    P011
11    P012
12    P013
13    P014
14    P015
15    P016
16    P017
17    P018
18    P018
19    P019
Name: Product_ID, dtype: str

In [46]:
# 2. Remove duplicate rows.

df = df.drop_duplicates()

df

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit_Price,Reorder_Level,Last_Update
0,P001,Laptop,Electronics,TechSource Ltd,25.0,850.0,10,2025-01-10
1,P002,laptop,electronics,Tech Source Ltd,15.0,870.0,8,10/02/2025
2,P003,SMARTPHONE,ELECTRONICS,MobileHub,50.0,650.0,20,2025/03/15
3,P004,Headphones,Electronics,SoundPro,5.0,45.0,12,15-04-2025
4,P005,Tablet,electronics,Mobile Hub,15.0,300.0,15,2025-05-01
5,P006,TABLET,Furniture,HomeStyle,18.0,120.0,5,2025/06/12
6,P007,Office Chair,furniTURE,Home Style,17.0,150.0,10,2025-13-01
7,P008,Desk,FURNITURE,FurniCo,100.0,99999.0,25,07/15/2025
8,P009,Printer,Electronics,PrintWorld,12.0,150.0,6,2025-07-20
9,P010,printer,electronics,Print World,12.0,150.0,6,2025-07-20
10,P011,Mouse,Accessories,TechSource Ltd,200.0,25.0,30,2025/08/01
11,P012,Keyboard,accessories,TechSOURCE Ltd,15.0,40.0,20,2025-08-05
12,P013,Monitor,Electronics,VisionTech,9.0,220.0,10,"August 10th, 2025"
13,P014,USB Cable,ACCESSORIES,CableKing,10.0,10555.0,50,2025-09-10
14,P015,Webcam,Electronics,Vision Tech,14.0,75.0,8,09-15-2025
15,P016,Router,Electronics,NetConnect,15.0,130.0,5,2025/10/05
16,P017,router,electronics,Net Connect,5.0,130.0,5,2025-10-05
17,P018,Speaker,Electronics,SoundPro,60.0,85.0,15,2025/11/11
19,P019,External Hard Drive,Electronics,DataStore,3.0,5000.0,7,2025-12-01

In [47]:
# 3. Standardize text: make all Product_Name, Category, and Supplier lowercase (or title case).
# Product_Name to lowercase or title case.

df["Product_Name"].to_list()

['Laptop',
 'laptop',
 'SMARTPHONE',
 'Headphones',
 'Tablet',
 'TABLET',
 'Office Chair',
 'Desk',
 'Printer',
 'printer',
 'Mouse',
 'Keyboard',
 'Monitor',
 'USB Cable',
 'Webcam',
 'Router',
 'router',
 'Speaker',
 'External Hard Drive']

In [48]:
df["Product_Name"] = df["Product_Name"].str.title()

df["Product_Name"]

0                  Laptop
1                  Laptop
2              Smartphone
3              Headphones
4                  Tablet
5                  Tablet
6            Office Chair
7                    Desk
8                 Printer
9                 Printer
10                  Mouse
11               Keyboard
12                Monitor
13              Usb Cable
14                 Webcam
15                 Router
16                 Router
17                Speaker
19    External Hard Drive
Name: Product_Name, dtype: str

In [49]:
#  Category to lowercase or title case.

df["Category"].to_list()

['Electronics',
 'electronics',
 'ELECTRONICS',
 'Electronics',
 'electronics',
 'Furniture',
 'furniTURE',
 'FURNITURE',
 'Electronics',
 'electronics',
 'Accessories',
 'accessories',
 'Electronics',
 'ACCESSORIES',
 'Electronics',
 'Electronics',
 'electronics',
 'Electronics',
 'Electronics']

In [50]:
df["Category"] = df["Category"].str.title()

df["Category"]

0     Electronics
1     Electronics
2     Electronics
3     Electronics
4     Electronics
5       Furniture
6       Furniture
7       Furniture
8     Electronics
9     Electronics
10    Accessories
11    Accessories
12    Electronics
13    Accessories
14    Electronics
15    Electronics
16    Electronics
17    Electronics
19    Electronics
Name: Category, dtype: str

In [51]:
# Standardize text: make all Product_Name, Category, and Supplier lowercase (or title case).
# Supplier to lowercase or title case.

df["Supplier"].to_list()

['TechSource Ltd',
 'Tech Source Ltd',
 'MobileHub',
 'SoundPro',
 'Mobile Hub',
 'HomeStyle',
 'Home Style',
 'FurniCo',
 'PrintWorld',
 'Print World',
 'TechSource Ltd',
 'TechSOURCE Ltd',
 'VisionTech',
 'CableKing',
 'Vision Tech',
 'NetConnect',
 'Net Connect',
 'SoundPro',
 'DataStore']

In [52]:
df["Supplier"] = df["Supplier"].str.title()

df["Supplier"]

0      Techsource Ltd
1     Tech Source Ltd
2           Mobilehub
3            Soundpro
4          Mobile Hub
5           Homestyle
6          Home Style
7             Furnico
8          Printworld
9         Print World
10     Techsource Ltd
11     Techsource Ltd
12         Visiontech
13          Cableking
14        Vision Tech
15         Netconnect
16        Net Connect
17           Soundpro
19          Datastore
Name: Supplier, dtype: str

In [53]:
df

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit_Price,Reorder_Level,Last_Update
0,P001,Laptop,Electronics,Techsource Ltd,25.0,850.0,10,2025-01-10
1,P002,Laptop,Electronics,Tech Source Ltd,15.0,870.0,8,10/02/2025
2,P003,Smartphone,Electronics,Mobilehub,50.0,650.0,20,2025/03/15
3,P004,Headphones,Electronics,Soundpro,5.0,45.0,12,15-04-2025
4,P005,Tablet,Electronics,Mobile Hub,15.0,300.0,15,2025-05-01
5,P006,Tablet,Furniture,Homestyle,18.0,120.0,5,2025/06/12
6,P007,Office Chair,Furniture,Home Style,17.0,150.0,10,2025-13-01
7,P008,Desk,Furniture,Furnico,100.0,99999.0,25,07/15/2025
8,P009,Printer,Electronics,Printworld,12.0,150.0,6,2025-07-20
9,P010,Printer,Electronics,Print World,12.0,150.0,6,2025-07-20
10,P011,Mouse,Accessories,Techsource Ltd,200.0,25.0,30,2025/08/01
11,P012,Keyboard,Accessories,Techsource Ltd,15.0,40.0,20,2025-08-05
12,P013,Monitor,Electronics,Visiontech,9.0,220.0,10,"August 10th, 2025"
13,P014,Usb Cable,Accessories,Cableking,10.0,10555.0,50,2025-09-10
14,P015,Webcam,Electronics,Vision Tech,14.0,75.0,8,09-15-2025
15,P016,Router,Electronics,Netconnect,15.0,130.0,5,2025/10/05
16,P017,Router,Electronics,Net Connect,5.0,130.0,5,2025-10-05
17,P018,Speaker,Electronics,Soundpro,60.0,85.0,15,2025/11/11
19,P019,External Hard Drive,Electronics,Datastore,3.0,5000.0,7,2025-12-01

In [54]:
# 4. Fix data types: convert columns to proper numeric or datetime types.
# for Quantity
df["Quantity"] = pd.to_numeric(df["Quantity"], errors="coerce")

df["Quantity"]

0      25.0
1      15.0
2      50.0
3       5.0
4      15.0
5      18.0
6      17.0
7     100.0
8      12.0
9      12.0
10    200.0
11     15.0
12      9.0
13     10.0
14     14.0
15     15.0
16      5.0
17     60.0
19      3.0
Name: Quantity, dtype: float64

In [55]:
# 4. Fix data types: convert columns to proper numeric or datetime types.
# for Unit_Price
df["Unit_Price"] = pd.to_numeric(df["Unit_Price"], errors="coerce")

df["Unit_Price"]

0       850.0
1       870.0
2       650.0
3        45.0
4       300.0
5       120.0
6       150.0
7     99999.0
8       150.0
9       150.0
10       25.0
11       40.0
12      220.0
13    10555.0
14       75.0
15      130.0
16      130.0
17       85.0
19     5000.0
Name: Unit_Price, dtype: float64

In [56]:
# 4. Fix data types: convert columns to proper numeric or datetime types.
# for Reorder_Level
df["Reorder_Level"] = pd.to_numeric(df["Reorder_Level"], errors="coerce")

df["Reorder_Level"]

0     10
1      8
2     20
3     12
4     15
5      5
6     10
7     25
8      6
9      6
10    30
11    20
12    10
13    50
14     8
15     5
16     5
17    15
19     7
Name: Reorder_Level, dtype: int64

In [57]:
#5. Handle incorrect values:
           # Replace or drop rows with negative or unrealistic prices/quantities.
# to replace use .fillana 
# to drop use .drop.na

In [58]:
# Standardize date formats in Last_Updated.

df["Last_Update"].to_list()

['2025-01-10',
 '10/02/2025',
 '2025/03/15',
 '15-04-2025',
 '2025-05-01',
 '2025/06/12',
 '2025-13-01',
 '07/15/2025',
 '2025-07-20',
 '2025-07-20',
 '2025/08/01',
 '2025-08-05',
 'August 10th, 2025',
 '2025-09-10',
 '09-15-2025',
 '2025/10/05',
 '2025-10-05',
 '2025/11/11',
 '2025-12-01']

In [59]:
# Standardize date formats in Last_Updated.

def date_parser(date_str):
    try:
        return parser.parse(date_str, dayfirst=True)
    except Exception:
        return pd.NaT
df["Last_Update"] = df["Last_Update"].apply(date_parser)

df["Last_Update"]

0    2025-10-01
1    2025-02-10
2    2025-03-15
3    2025-04-15
4    2025-01-05
5    2025-12-06
6    2025-01-13
7    2025-07-15
8    2025-07-20
9    2025-07-20
10   2025-01-08
11   2025-05-08
12   2025-08-10
13   2025-10-09
14   2025-09-15
15   2025-05-10
16   2025-05-10
17   2025-11-11
19   2025-01-12
Name: Last_Update, dtype: datetime64[us]

In [60]:
# Part 4: Analyze and Sort the Data
# Use Pandas to answer the following: 
# 1. Which products need restocking (where Quantity < Reorder_Level)? 
# Products needing restock

restock_products = df[df["Quantity"] < df["Reorder_Level"]]

print("Products Needing Restock:")
print(restock_products[["Product_Name", "Quantity", "Reorder_Level"]])

Products Needing Restock:
           Product_Name  Quantity  Reorder_Level
3            Headphones       5.0             12
11             Keyboard      15.0             20
12              Monitor       9.0             10
13            Usb Cable      10.0             50
19  External Hard Drive       3.0              7

In [61]:
# 2. What is the average unit price per category?
# Average Unit Price per Category

avg_price = df.groupby("Category")["Unit_Price"].mean()

print("\nAverage Unit Price Per Category:")
print(avg_price)

Average Unit Price Per Category:
Category
Accessories     3540.000000
Electronics      665.769231
Furniture      33423.000000
Name: Unit_Price, dtype: float64

In [62]:
# 3. Which supplier provides the most products? 
# Supplier with Most Products

supplier_count = df["Supplier"].value_counts()

print("\nSupplier Providing Most Products:")
print(supplier_count)

Supplier Providing Most Products:
Supplier
Techsource Ltd     3
Soundpro           2
Tech Source Ltd    1
Mobilehub          1
Mobile Hub         1
Homestyle          1
Home Style         1
Furnico            1
Printworld         1
Print World        1
Visiontech         1
Cableking          1
Vision Tech        1
Netconnect         1
Net Connect        1
Datastore          1
Name: count, dtype: int64

In [63]:
# 4. List the top 5 most expensive products. 
# Top 5 Most Expensive Products

top_expensive = df.nlargest(5, "Unit_Price")

print("\nTop 5 Most Expensive Products:")
print(top_expensive[["Product_Name", "Unit_Price"]])

Top 5 Most Expensive Products:
           Product_Name  Unit_Price
7                  Desk     99999.0
13            Usb Cable     10555.0
19  External Hard Drive      5000.0
1                Laptop       870.0
0                Laptop       850.0

In [64]:
# 5. Sort the cleaned dataset by Category and then by Unit_Price in descending order.
# Sort by Category and Unit Price

sorted_df = df.sort_values(
    by=["Category", "Unit_Price"],
    ascending=[True, False]
)

print("\nSorted Dataset:")
print(sorted_df)

Sorted Dataset:
   Product_ID         Product_Name     Category         Supplier  Quantity  \
13       P014            Usb Cable  Accessories        Cableking      10.0
11       P012             Keyboard  Accessories   Techsource Ltd      15.0
10       P011                Mouse  Accessories   Techsource Ltd     200.0
19       P019  External Hard Drive  Electronics        Datastore       3.0
1        P002               Laptop  Electronics  Tech Source Ltd      15.0
0        P001               Laptop  Electronics   Techsource Ltd      25.0
2        P003           Smartphone  Electronics        Mobilehub      50.0
4        P005               Tablet  Electronics       Mobile Hub      15.0
12       P013              Monitor  Electronics       Visiontech       9.0
8        P009              Printer  Electronics       Printworld      12.0
9        P010              Printer  Electronics      Print World      12.0
15       P016               Router  Electronics       Netconnect      15.0
16       P017               Router  Electronics      Net Connect       5.0
17       P018              Speaker  Electronics         Soundpro      60.0
14       P015               Webcam  Electronics      Vision Tech      14.0
3        P004           Headphones  Electronics         Soundpro       5.0
7        P008                 Desk    Furniture          Furnico     100.0
6        P007         Office Chair    Furniture       Home Style      17.0
5        P006               Tablet    Furniture        Homestyle      18.0

    Unit_Price  Reorder_Level Last_Update
13     10555.0             50  2025-10-09
11        40.0             20  2025-05-08
10        25.0             30  2025-01-08
19      5000.0              7  2025-01-12
1        870.0              8  2025-02-10
0        850.0             10  2025-10-01
2        650.0             20  2025-03-15
4        300.0             15  2025-01-05
12       220.0             10  2025-08-10
8        150.0              6  2025-07-20
9        150.0              6  2025-07-20
15       130.0              5  2025-05-10
16       130.0              5  2025-05-10
17        85.0             15  2025-11-11
14        75.0              8  2025-09-15
3         45.0             12  2025-04-15
7      99999.0             25  2025-07-15
6        150.0             10  2025-01-13
5        120.0              5  2025-12-06

# Deliverables Submit the following files: 
# 1. A Jupyter Notebook (inventory_analysis.ipynb) with: Your Pandas code and explanations Answers to all analysis questions
Based on the dataset, several data quality and inventory management issues were identified. The dataset contains inconsistencies such as duplicated 
records, mixed capitalization in product names and categories, invalid dates, missing values, wrong data types, and unrealistic values in quantities 
and prices. These issues highlight the importance of data cleaning before performing analysis.
    
From the inventory analysis, some products were found to be below their reorder levels, indicating that they need urgent restocking to avoid stock 
shortages. A few products also had missing stock quantities, which may affect sales operations if not addressed quickly.

The pricing analysis showed major irregularities like high prices such as 99999 and , which are unrealistic and could distort financial analysis. 
After cleaning the data, the average unit price across categories became more reliable for business reporting.

Supplier analysis revealed that some suppliers provide more products than others, making them key partners in the supply chain. 
However, supplier names also contained spelling inconsistencies, which could lead to inaccurate reporting if not standardized.

Overall, the dataset demonstrates common real-world data problems and shows how data cleaning techniques in Pandas can improve data accuracy, 
consistency, and business decision-making